version: "2"
linters:
  default: all
  disable:
    - arangolint
    - cyclop
    - depguard
    - funcorder
    - funlen
    - gocognit
    - gocyclo
    - godox
    - nlreturn
    - unqueryvet
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - ifElseChain
    godot:
      scope: all
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 170
    nestif:
      min-complexity: 15
    nolintlint:
      require-specific: true
      allow-unused: false
    staticcheck:
      checks:
        - all
    tagalign:
      strict: true
    testifylint:
      require-error:
        fn-pattern: ^(NoError|NotErrorIs)$
  exclusions:
    generated: strict
    warn-unused: true
    rules:
      - linters:
          - gochecknoglobals
          - goconst
          - testpackage
        path: stack_test\.go
      - linters:
          - err113
          - errcheck
          - errname
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gocritic
          - godot
          - lll
          - maintidx
          - revive
          - staticcheck
        path: (errors|format)_.*test\.go
      - linters:
          - goconst
          - godot
          - testableexamples
        path: example_test\.go
      - linters:
          - err113
        path: stdlib\.go
      - linters:
          - godot
          - nonamedreturns
        path: example_join_test\.go
      - linters:
          - testableexamples
        path: example_stack_test\.go
      - linters:
          - testpackage
        path: private_test\.go
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    # - gci
    # - golines
    # - swaggo
  settings:
    goimports:
      local-prefixes:
        - gitlab.com/tozd/go/errors
  exclusions:
    generated: strict
    warn-unused: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  timeout: 4m