linters-settings:
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - io.WriteString
    enable-all: true
  gocritic:
    disabled-checks:
      - ifElseChain
  godot:
    scope: all
  gofumpt:
    go: "1.20"
  goimports:
    local-prefixes: gitlab.com/tozd/go/errors
  gosimple:
    go: "1.20"
    checks:
      - all
  govet:
    check-shadowing: true
  lll:
    line-length: 170
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true
  stylecheck:
    go: "1.20"
    checks:
      - all
  staticcheck:
    go: "1.20"
    checks:
      - all
  unused:
    go: "1.20"

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    # - bodyclose
    # - containedctx
    # - contextcheck
    # - durationcheck
    # - err113
    # - errname
    # - errorlint
    # - gocheckcompilerdirectives
    # - importas
    # - noctx
    # - nosprintfhostport
    # - tagliatelle
    # - wrapcheck
    # - zerologlint

issues:
  exclude-rules:
    - path: stack_test\.go
      linters:
        - testpackage
    - path: json_test\.go
      linters:
        - lll
    - path: errors_.*test\.go
      linters:
        - revive
        - staticcheck
        - gocritic
        - lll
        - godot
    - path: example_test\.go
      linters:
        - godot
