git:
  changelog: ""
  requireCleanWorkingDir: true
  requireBranch: main
  requireUpstream: true
  requireCommits: true
  addUntrackedFiles: false
  commit: true
  commitMessage: "Release v${version}."
  tag: true
  tagName: "v${version}"
  tagAnnotation: "Release v${version}."
  push: true
plugins:
  "@release-it/keep-a-changelog":
    filename: CHANGELOG.md
    addUnreleased: true
    addVersionUrl: true
    head: main
npm:
  publish: true
github:
  release: false
gitlab:
  release: false
